import React from 'react'
import ReactDOM from 'react-dom/client'
import {App} from './App'
import './styles.css'
import './login.css'
import './settings.css'
import './sites.css'
import './charts.css'
import './events.css'
import 'leaflet/dist/leaflet.css'
import './maps.css'
import './configuration.css'
import './sso.css'
import './roles.css'
import './remediation.css'
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
